package View;

import Model.Pokemon;

import java.util.ArrayList;
import java.util.List;

public class Lista151Pokes{

    public Lista151Pokes() {
    }

    public List<Pokemon> gerarListaPokes() {
        List<Pokemon> listPokemon = new ArrayList<>();
        Pokemon Bulbasaur = new Pokemon("Bulbasaur", "Planta", "Venenoso", 90, 26);
        listPokemon.add(Bulbasaur);
        Pokemon Ivysaur = new Pokemon("Ivysaur", "Planta", "Venenoso", 23, 64);
        listPokemon.add(Ivysaur);
        Pokemon Venusaur = new Pokemon("Venusaur", "Planta", "Venenoso", 38, 45);
        listPokemon.add(Venusaur);
        Pokemon Charmander = new Pokemon("Charmander", "Fogo", null, 27, 24);
        listPokemon.add(Charmander);
        Pokemon Charmeleon = new Pokemon("Charmeleon", "Fogo", null, 96, 79);
        listPokemon.add(Charmeleon);
        Pokemon Charizard = new Pokemon("Charizard", "Fogo", "Voador", 56, 76);
        listPokemon.add(Charizard);
        Pokemon Squirtle = new Pokemon("Squirtle", "Agua", null, 69, 36);
        listPokemon.add(Squirtle);
        Pokemon Wartortle = new Pokemon("Wartortle", "Agua", null, 47, 10);
        listPokemon.add(Wartortle);
        Pokemon Blastoise = new Pokemon("Blastoise", "Agua", null, 71, 12);
        listPokemon.add(Blastoise);
        Pokemon Caterpie = new Pokemon("Caterpie", "Inseto", null, 44, 55);
        listPokemon.add(Caterpie);
        Pokemon Metapod = new Pokemon("Metapod", "Inseto", null, 19, 36);
        listPokemon.add(Metapod);
        Pokemon Butterfree = new Pokemon("Butterfree", "Inseto", "Voador", 10, 32);
        listPokemon.add(Butterfree);
        Pokemon Weedle = new Pokemon("Weedle", "Inseto", "Venenoso", 29, 18);
        listPokemon.add(Weedle);
        Pokemon Kakuna = new Pokemon("Kakuna", "Inseto", "Venenoso", 18, 95);
        listPokemon.add(Kakuna);
        Pokemon Beedrill = new Pokemon("Beedrill", "Inseto", "Venenoso", 14, 87);
        listPokemon.add(Beedrill);
        Pokemon Pidgey = new Pokemon("Pidgey", "Normal", "Voador", 12, 76);
        listPokemon.add(Pidgey);
        Pokemon Pidgeotto = new Pokemon("Pidgeotto", "Normal", "Voador", 55, 5);
        listPokemon.add(Pidgeotto);
        Pokemon Pidgeot = new Pokemon("Pidgeot", "Normal", "Voador", 4, 12);
        listPokemon.add(Pidgeot);
        Pokemon Rattata = new Pokemon("Rattata", "Normal", null, 28, 65);
        listPokemon.add(Rattata);
        Pokemon Raticate = new Pokemon("Raticate", "Normal", null, 18, 90);
        listPokemon.add(Raticate);
        Pokemon Spearow = new Pokemon("Spearow", "Normal", "Voador", 13, 40);
        listPokemon.add(Spearow);
        Pokemon Fearow = new Pokemon("Fearow", "Normal", "Voador", 13, 94);
        listPokemon.add(Fearow);
        Pokemon Ekans = new Pokemon("Ekans", "Venenoso", null, 84, 62);
        listPokemon.add(Ekans);
        Pokemon Arbok = new Pokemon("Arbok", "Venenoso", null, 89, 42);
        listPokemon.add(Arbok);
        Pokemon Pikachu = new Pokemon("Pikachu", "Eletrico", null, 28, 91);
        listPokemon.add(Pikachu);
        Pokemon Raichu = new Pokemon("Raichu", "Eletrico", null, 55, 67);
        listPokemon.add(Raichu);
        Pokemon Sandshrew = new Pokemon("Sandshrew", "Terrestre", null, 50, 30);
        listPokemon.add(Sandshrew);
        Pokemon Sandslash = new Pokemon("Sandslash", "Terrestre", null, 74, 79);
        listPokemon.add(Sandslash);
        Pokemon NidoranF = new Pokemon("NidoranF", "Venenoso", null, 31, 22);
        listPokemon.add(NidoranF);
        Pokemon Nidorina = new Pokemon("Nidorina", "Venenoso", null, 72, 93);
        listPokemon.add(Nidorina);
        Pokemon Nidoqueen = new Pokemon("Nidoqueen", "Venenoso", "Terrestre", 84, 78);
        listPokemon.add(Nidoqueen);
        Pokemon NidoranM = new Pokemon("NidoranM", "Venenoso", null, 24, 33);
        listPokemon.add(NidoranM);
        Pokemon Nidorino = new Pokemon("Nidorino", "Venenoso", null, 52, 32);
        listPokemon.add(Nidorino);
        Pokemon Nidoking = new Pokemon("Nidoking", "Venenoso", "Terrestre", 24, 18);
        listPokemon.add(Nidoking);
        Pokemon Clefairy = new Pokemon("Clefairy", "Normal", null, 80, 13);
        listPokemon.add(Clefairy);
        Pokemon Clefable = new Pokemon("Clefable", "Normal", null, 68, 6);
        listPokemon.add(Clefable);
        Pokemon Vulpix = new Pokemon("Vulpix", "Fogo", null, 19, 17);
        listPokemon.add(Vulpix);
        Pokemon Ninetales = new Pokemon("Ninetales", "Fogo", null, 34, 62);
        listPokemon.add(Ninetales);
        Pokemon Jigglypuff = new Pokemon("Jigglypuff", "Normal", null, 15, 29);
        listPokemon.add(Jigglypuff);
        Pokemon Wigglytuff = new Pokemon("Wigglytuff", "Normal", null, 89, 93);
        listPokemon.add(Wigglytuff);
        Pokemon Zubat = new Pokemon("Zubat", "Venenoso", "Voador", 68, 44);
        listPokemon.add(Zubat);
        Pokemon Golbat = new Pokemon("Golbat", "Venenoso", "Voador", 17, 12);
        listPokemon.add(Golbat);
        Pokemon Oddish = new Pokemon("Oddish", "Planta", "Venenoso", 97, 93);
        listPokemon.add(Oddish);
        Pokemon Gloom = new Pokemon("Gloom", "Planta", "Venenoso", 48, 24);
        listPokemon.add(Gloom);
        Pokemon Vileplume = new Pokemon("Vileplume", "Planta", "Venenoso", 38, 31);
        listPokemon.add(Vileplume);
        Pokemon Paras = new Pokemon("Paras", "Inseto", "Planta", 71, 63);
        listPokemon.add(Paras);
        Pokemon Parasect = new Pokemon("Parasect", "Inseto", "Planta", 57, 42);
        listPokemon.add(Parasect);
        Pokemon Venonat = new Pokemon("Venonat", "Inseto", "Venenoso", 19, 100);
        listPokemon.add(Venonat);
        Pokemon Venomoth = new Pokemon("Venomoth", "Inseto", "Venenoso", 48, 12);
        listPokemon.add(Venomoth);
        Pokemon Diglett = new Pokemon("Diglett", "Terrestre", null, 52, 57);
        listPokemon.add(Diglett);
        Pokemon Dugtrio = new Pokemon("Dugtrio", "Terrestre", null, 43, 45);
        listPokemon.add(Dugtrio);
        Pokemon Meowth = new Pokemon("Meowth", "Normal", null, 57, 92);
        listPokemon.add(Meowth);
        Pokemon Persian = new Pokemon("Persian", "Normal", null, 84, 94);
        listPokemon.add(Persian);
        Pokemon Psyduck = new Pokemon("Psyduck", "Agua", null, 2, 55);
        listPokemon.add(Psyduck);
        Pokemon Golduck = new Pokemon("Golduck", "Agua", null, 13, 36);
        listPokemon.add(Golduck);
        Pokemon Mankey = new Pokemon("Mankey", "Lutador", null, 78, 11);
        listPokemon.add(Mankey);
        Pokemon Primeape = new Pokemon("Primeape", "Lutador", null, 59, 70);
        listPokemon.add(Primeape);
        Pokemon Growlithe = new Pokemon("Growlithe", "Fogo", null, 62, 60);
        listPokemon.add(Growlithe);
        Pokemon Arcanine = new Pokemon("Arcanine", "Fogo", null, 72, 54);
        listPokemon.add(Arcanine);
        Pokemon Poliwag = new Pokemon("Poliwag", "Agua", null, 99, 41);
        listPokemon.add(Poliwag);
        Pokemon Poliwhirl = new Pokemon("Poliwhirl", "Agua", null, 90, 2);
        listPokemon.add(Poliwhirl);
        Pokemon Poliwrath = new Pokemon("Poliwrath", "Agua", "Lutador", 12, 16);
        listPokemon.add(Poliwrath);
        Pokemon Abra = new Pokemon("Abra", "Psiquico", null, 8, 16);
        listPokemon.add(Abra);
        Pokemon Kadabra = new Pokemon("Kadabra", "Psiquico", null, 13, 71);
        listPokemon.add(Kadabra);
        Pokemon Alakazam = new Pokemon("Alakazam", "Psiquico", null, 4, 48);
        listPokemon.add(Alakazam);
        Pokemon Machop = new Pokemon("Machop", "Lutador", null, 68, 100);
        listPokemon.add(Machop);
        Pokemon Machoke = new Pokemon("Machoke", "Lutador", null, 32, 34);
        listPokemon.add(Machoke);
        Pokemon Machamp = new Pokemon("Machamp", "Lutador", null, 79, 82);
        listPokemon.add(Machamp);
        Pokemon Bellsprout = new Pokemon("Bellsprout", "Planta", "Venenoso", 95, 91);
        listPokemon.add(Bellsprout);
        Pokemon Weepinbell = new Pokemon("Weepinbell", "Planta", "Venenoso", 25, 13);
        listPokemon.add(Weepinbell);
        Pokemon Victreebel = new Pokemon("Victreebel", "Planta", "Venenoso", 74, 67);
        listPokemon.add(Victreebel);
        Pokemon Tentacool = new Pokemon("Tentacool", "Agua", "Venenoso", 67, 2);
        listPokemon.add(Tentacool);
        Pokemon Tentacruel = new Pokemon("Tentacruel", "Agua", "Venenoso", 73, 97);
        listPokemon.add(Tentacruel);
        Pokemon Geodude = new Pokemon("Geodude", "Pedra", "Terrestre", 55, 27);
        listPokemon.add(Geodude);
        Pokemon Graveler = new Pokemon("Graveler", "Pedra", "Terrestre", 97, 48);
        listPokemon.add(Graveler);
        Pokemon Golem = new Pokemon("Golem", "Pedra", "Terrestre", 63, 21);
        listPokemon.add(Golem);
        Pokemon Ponyta = new Pokemon("Ponyta", "Fogo", null, 10, 73);
        listPokemon.add(Ponyta);
        Pokemon Rapidash = new Pokemon("Rapidash", "Fogo", null, 68, 92);
        listPokemon.add(Rapidash);
        Pokemon Slowpoke = new Pokemon("Slowpoke", "Agua", "Psiquico", 86, 32);
        listPokemon.add(Slowpoke);
        Pokemon Slowbro = new Pokemon("Slowbro", "Agua", "Psiquico", 15, 29);
        listPokemon.add(Slowbro);
        Pokemon Magnemite = new Pokemon("Magnemite", "Eletrico", null, 81, 74);
        listPokemon.add(Magnemite);
        Pokemon Magneton = new Pokemon("Magneton", "Eletrico", null, 94, 12);
        listPokemon.add(Magneton);
        Pokemon Farfetchd = new Pokemon("Farfetch'd", "Normal", "Voador", 43, 14);
        listPokemon.add(Farfetchd);
        Pokemon Doduo = new Pokemon("Doduo", "Normal", "Voador", 64, 85);
        listPokemon.add(Doduo);
        Pokemon Dodrio = new Pokemon("Dodrio", "Normal", "Voador", 27, 29);
        listPokemon.add(Dodrio);
        Pokemon Seel = new Pokemon("Seel", "Agua", null, 12, 40);
        listPokemon.add(Seel);
        Pokemon Dewgong = new Pokemon("Dewgong", "Agua", "Gelo", 11, 28);
        listPokemon.add(Dewgong);
        Pokemon Grimer = new Pokemon("Grimer", "Venenoso", null, 88, 61);
        listPokemon.add(Grimer);
        Pokemon Muk = new Pokemon("Muk", "Venenoso", null, 70, 100);
        listPokemon.add(Muk);
        Pokemon Shellder = new Pokemon("Shellder", "Agua", null, 51, 74);
        listPokemon.add(Shellder);
        Pokemon Cloyster = new Pokemon("Cloyster", "Agua", "Gelo", 41, 44);
        listPokemon.add(Cloyster);
        Pokemon Gastly = new Pokemon("Gastly", "Fantasma", "Venenoso", 48, 38);
        listPokemon.add(Gastly);
        Pokemon Haunter = new Pokemon("Haunter", "Fantasma", "Venenoso", 18, 16);
        listPokemon.add(Haunter);
        Pokemon Gengar = new Pokemon("Gengar", "Fantasma", "Venenoso", 22, 90);
        listPokemon.add(Gengar);
        Pokemon Onix = new Pokemon("Onix", "Pedra", "Terrestre", 83, 54);
        listPokemon.add(Onix);
        Pokemon Drowzee = new Pokemon("Drowzee", "Psiquico", null, 68, 20);
        listPokemon.add(Drowzee);
        Pokemon Hypno = new Pokemon("Hypno", "Psiquico", null, 95, 2);
        listPokemon.add(Hypno);
        Pokemon Krabby = new Pokemon("Krabby", "Agua", null, 26, 12);
        listPokemon.add(Krabby);
        Pokemon Kingler = new Pokemon("Kingler", "Agua", null, 65, 96);
        listPokemon.add(Kingler);
        Pokemon Voltorb = new Pokemon("Voltorb", "Eletrico", null, 92, 80);
        listPokemon.add(Voltorb);
        Pokemon Electrode = new Pokemon("Electrode", "Eletrico", null, 50, 49);
        listPokemon.add(Electrode);
        Pokemon Exeggcute = new Pokemon("Exeggcute", "Planta", "Psiquico", 64, 34);
        listPokemon.add(Exeggcute);
        Pokemon Exeggutor = new Pokemon("Exeggutor", "Planta", "Psiquico", 21, 76);
        listPokemon.add(Exeggutor);
        Pokemon Cubone = new Pokemon("Cubone", "Terrestre", null, 19, 48);
        listPokemon.add(Cubone);
        Pokemon Marowak = new Pokemon("Marowak", "Terrestre", null, 85, 84);
        listPokemon.add(Marowak);
        Pokemon Hitmonlee = new Pokemon("Hitmonlee", "Lutador", null, 56, 71);
        listPokemon.add(Hitmonlee);
        Pokemon Hitmonchan = new Pokemon("Hitmonchan", "Lutador", null, 44, 44);
        listPokemon.add(Hitmonchan);
        Pokemon Lickitung = new Pokemon("Lickitung", "Normal", null, 86, 11);
        listPokemon.add(Lickitung);
        Pokemon Koffing = new Pokemon("Koffing", "Venenoso", null, 98, 63);
        listPokemon.add(Koffing);
        Pokemon Weezing = new Pokemon("Weezing", "Venenoso", null, 81, 93);
        listPokemon.add(Weezing);
        Pokemon Rhyhorn = new Pokemon("Rhyhorn", "Terrestre", "Pedra", 69, 13);
        listPokemon.add(Rhyhorn);
        Pokemon Rhydon = new Pokemon("Rhydon", "Terrestre", "Pedra", 31, 67);
        listPokemon.add(Rhydon);
        Pokemon Chansey = new Pokemon("Chansey", "Normal", null, 27, 41);
        listPokemon.add(Chansey);
        Pokemon Tangela = new Pokemon("Tangela", "Planta", null, 69, 86);
        listPokemon.add(Tangela);
        Pokemon Kangaskhan = new Pokemon("Kangaskhan", "Normal", null, 43, 22);
        listPokemon.add(Kangaskhan);
        Pokemon Horsea = new Pokemon("Horsea", "Agua", null, 91, 79);
        listPokemon.add(Horsea);
        Pokemon Seadra = new Pokemon("Seadra", "Agua", null, 35, 57);
        listPokemon.add(Seadra);
        Pokemon Goldeen = new Pokemon("Goldeen", "Agua", null, 21, 38);
        listPokemon.add(Goldeen);
        Pokemon Seaking = new Pokemon("Seaking", "Agua", null, 65, 46);
        listPokemon.add(Seaking);
        Pokemon Staryu = new Pokemon("Staryu", "Agua", null, 70, 60);
        listPokemon.add(Staryu);
        Pokemon Starmie = new Pokemon("Starmie", "Agua", "Psiquico", 64, 39);
        listPokemon.add(Starmie);
        Pokemon MrMime = new Pokemon("Mr. Mime", "Psiquico", null, 67, 72);
        listPokemon.add(MrMime);
        Pokemon Scyther = new Pokemon("Scyther", "Inseto", "Voador", 12, 85);
        listPokemon.add(Scyther);
        Pokemon Jynx = new Pokemon("Jynx", "Gelo", "Psiquico", 85, 93);
        listPokemon.add(Jynx);
        Pokemon Electabuzz = new Pokemon("Electabuzz", "Eletrico", null, 78, 64);
        listPokemon.add(Electabuzz);
        Pokemon Magmar = new Pokemon("Magmar", "Fogo", null, 97, 50);
        listPokemon.add(Magmar);
        Pokemon Pinsir = new Pokemon("Pinsir", "Inseto", null, 11, 77);
        listPokemon.add(Pinsir);
        Pokemon Tauros = new Pokemon("Tauros", "Normal", null, 96, 84);
        listPokemon.add(Tauros);
        Pokemon Magikarp = new Pokemon("Magikarp", "Agua", null, 55, 51);
        listPokemon.add(Magikarp);
        Pokemon Gyarados = new Pokemon("Gyarados", "Agua", "Voador", 19, 52);
        listPokemon.add(Gyarados);
        Pokemon Lapras = new Pokemon("Lapras", "Agua", "Gelo", 12, 21);
        listPokemon.add(Lapras);
        Pokemon Ditto = new Pokemon("Ditto", "Normal", null, 62, 67);
        listPokemon.add(Ditto);
        Pokemon Eevee = new Pokemon("Eevee", "Normal", null, 63, 42);
        listPokemon.add(Eevee);
        Pokemon Vaporeon = new Pokemon("Vaporeon", "Agua", null, 72, 33);
        listPokemon.add(Vaporeon);
        Pokemon Jolteon = new Pokemon("Jolteon", "Eletrico", null, 21, 96);
        listPokemon.add(Jolteon);
        Pokemon Flareon = new Pokemon("Flareon", "Fogo", null, 86, 28);
        listPokemon.add(Flareon);
        Pokemon Porygon = new Pokemon("Porygon", "Normal", null, 77, 54);
        listPokemon.add(Porygon);
        Pokemon Omanyte = new Pokemon("Omanyte", "Pedra", "Agua", 40, 73);
        listPokemon.add(Omanyte);
        Pokemon Omastar = new Pokemon("Omastar", "Pedra", "Agua", 87, 57);
        listPokemon.add(Omastar);
        Pokemon Kabuto = new Pokemon("Kabuto", "Pedra", "Agua", 37, 61);
        listPokemon.add(Kabuto);
        Pokemon Kabutops = new Pokemon("Kabutops", "Pedra", "Agua", 96, 54);
        listPokemon.add(Kabutops);
        Pokemon Aerodactyl = new Pokemon("Aerodactyl", "Pedra", "Voador", 61, 28);
        listPokemon.add(Aerodactyl);
        Pokemon Snorlax = new Pokemon("Snorlax", "Normal", null, 70, 14);
        listPokemon.add(Snorlax);
        Pokemon Articuno = new Pokemon("Articuno", "Gelo", "Voador", 48, 22);
        listPokemon.add(Articuno);
        Pokemon Zapdos = new Pokemon("Zapdos", "Eletrico", "Voador", 96, 37);
        listPokemon.add(Zapdos);
        Pokemon Moltres = new Pokemon("Moltres", "Fogo", "Voador", 11, 68);
        listPokemon.add(Moltres);
        Pokemon Dratini = new Pokemon("Dratini", "Dragao", null, 55, 58);
        listPokemon.add(Dratini);
        Pokemon Dragonair = new Pokemon("Dragonair", "Dragao", null, 54, 29);
        listPokemon.add(Dragonair);
        Pokemon Dragonite = new Pokemon("Dragonite", "Dragao", "Voador", 85, 76);
        listPokemon.add(Dragonite);
        Pokemon Mewtwo = new Pokemon("Mewtwo", "Psiquico", null, 34, 98);
        listPokemon.add(Mewtwo);
        Pokemon Mew = new Pokemon("Mew", "Psiquico", null, 83, 32);
        listPokemon.add(Mew);
        // Alola
        Pokemon RattataAlola = new Pokemon("RattataAlola", "Noturno", "Normal", 26, 95);
        listPokemon.add(RattataAlola);
        Pokemon RaticateAlola = new Pokemon("RaticateAlola", "Noturno", "Normal", 92, 48);
        listPokemon.add(RaticateAlola);
        Pokemon RaichuAlola = new Pokemon("RaichuAlola", "Eletrico", "Psiquico", 68, 50);
        listPokemon.add(RaichuAlola);
        Pokemon SandshrewAlola = new Pokemon("SandshrewAlola", "Gelo", "Aco", 19, 11);
        listPokemon.add(SandshrewAlola);
        Pokemon SandslashAlola = new Pokemon("SandslashAlola", "Gelo", "Aco", 68, 89);
        listPokemon.add(SandslashAlola);
        Pokemon VulpixAlola = new Pokemon("VulpixAlola", "Gelo", null, 82, 22);
        listPokemon.add(VulpixAlola);
        Pokemon NinetalesAlola = new Pokemon("NinetalesAlola", "Gelo", "Fada", 19, 78);
        listPokemon.add(NinetalesAlola);
        Pokemon DiglettAlola = new Pokemon("DiglettAlola", "Terrestre", "Aco", 37, 74);
        listPokemon.add(DiglettAlola);
        Pokemon DugtrioAlola = new Pokemon("DugtrioAlola", "Terrestre", "Aco", 43, 26);
        listPokemon.add(DugtrioAlola);
        Pokemon MeowthAlola = new Pokemon("MeowthAlola", "Noturno", null, 54, 18);
        listPokemon.add(MeowthAlola);
        Pokemon PersianAlola = new Pokemon("PersianAlola", "Noturno", null, 41, 57);
        listPokemon.add(PersianAlola);
        Pokemon GeodudeAlola = new Pokemon("GeodudeAlola", "Pedra", "Eletrico", 46, 30);
        listPokemon.add(GeodudeAlola);
        Pokemon GravelerAlola = new Pokemon("GravelerAlola", "Pedra", "Eletrico", 66, 79);
        listPokemon.add(GravelerAlola);
        Pokemon GolemAlola = new Pokemon("GolemAlola", "Pedra", "Eletrico", 100, 48);
        listPokemon.add(GolemAlola);
        Pokemon GrimerAlola = new Pokemon("GrimerAlola", "Venenoso", "Noturno", 88, 93);
        listPokemon.add(GrimerAlola);
        Pokemon MukAlola = new Pokemon("MukAlola", "Venenoso", "Noturno", 77, 11);
        listPokemon.add(MukAlola);
        Pokemon ExeggutorAlola = new Pokemon("ExeggutorAlola", "Planta", "Dragao", 95, 80);
        listPokemon.add(ExeggutorAlola);
        Pokemon MarowakAlola = new Pokemon("MarowakAlola", "Fogo", "Fantasma", 48, 94);
        listPokemon.add(MarowakAlola);

// Galar
        Pokemon MeowthGalar = new Pokemon("MeowthGalar", "Aco", null, 23, 27);
        listPokemon.add(MeowthGalar);
        Pokemon PonytaGalar = new Pokemon("PonytaGalar", "Psiquico", null, 43, 24);
        listPokemon.add(PonytaGalar);
        Pokemon RapidashGalar = new Pokemon("RapidashGalar", "Psiquico", "Fada", 23, 80);
        listPokemon.add(RapidashGalar);
        Pokemon FarfetchdGalar = new Pokemon("FarfetchdGalar", "Lutador", null, 29, 44);
        listPokemon.add(FarfetchdGalar);
        Pokemon MrMimeGalar = new Pokemon("MrMimeGalar", "Gelo", "Psiquico", 46, 87);
        listPokemon.add(MrMimeGalar);
        Pokemon SlowpokeGalar = new Pokemon("SlowpokeGalar", "Psiquico", null, 36, 53);
        listPokemon.add(SlowpokeGalar);

// Hisui
        Pokemon VoltorbHisui = new Pokemon("VoltorbHisui", "Planta", "Eletrico", 36, 97);
        listPokemon.add(VoltorbHisui);
        Pokemon ElectrodeHisui = new Pokemon("ElectrodeHisui", "Planta", "Eletrico", 91, 43);
        listPokemon.add(ElectrodeHisui);
        Pokemon GrowlitheHisui = new Pokemon("GrowlitheHisui", "Fogo", "Pedra", 74, 72);
        listPokemon.add(GrowlitheHisui);
        Pokemon ArcanineHisui = new Pokemon("ArcanineHisui", "Fogo", "Pedra", 42, 16);
        listPokemon.add(ArcanineHisui);
        return listPokemon;
    }

}
